.SEGMENT "ZEROPAGE"
POINTER:.BYTE $01
		.BYTE $02
		.BYTE $03
		.BYTE $04
		.BYTE $05

.SEGMENT "CODE"
RESET:
		LDX #$05
		LDA #$00
		TAY
LOOP:	STA POINTER,Y
		INY
		DEX
		BNE LOOP
		BRK

.SEGMENT "VEC_NMI"
	.WORD $0F00     ; NMI
.SEGMENT "VEC_RST"
	.WORD RESET     ; RESET
.SEGMENT "VEC_IRQBRK"
	.WORD $0000     ; BRK/IRQ