.SEGMENT "ZEROPAGE"

.SEGMENT "CODE"
RESET:
		LDA #$01
		STA $0200
		LDA #$05
		STA $0201
		LDA #$08
		STA $0202
		BRK

.SEGMENT "VEC_NMI"
	.WORD $0F00     ; NMI
.SEGMENT "VEC_RST"
	.WORD RESET     ; RESET
.SEGMENT "VEC_IRQBRK"
	.WORD $0000     ; BRK/IRQ